# Generated by Django 4.2.29 on 2026-04-17 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_project_current_phase'),
        ('operations', '0002_multi_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.PositiveIntegerField(help_text='Progress percentage 0-100')),
                ('phase', models.CharField(choices=[('preparation', 'เตรียมงาน (Preparation)'), ('foundation', 'ฐานราก (Foundation)'), ('structure', 'โครงสร้าง (Structure)'), ('roofing', 'หลังคา (Roofing)'), ('electrical', 'ไฟฟ้า (Electrical)'), ('plumbing', 'ประปา (Plumbing)'), ('plastering', 'ฉาบปูน (Plastering)'), ('tiling', 'กระเบื้อง (Tiling)'), ('painting', 'ทาสี (Painting)'), ('finishing', 'ตกแต่ง (Finishing)'), ('cleanup', 'ทำความสะอาด (Cleanup)'), ('handover', 'ส่งมอบ (Handover)')], default='preparation', max_length=30)),
                ('work_description', models.TextField(help_text='รายละเอียดงานวันนี้')),
                ('worker_count', models.PositiveIntegerField(default=0, help_text='จำนวนคนงานที่ใช้วันนี้')),
                ('issues', models.TextField(blank=True, help_text='ปัญหาที่พบ (ถ้ามี)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='core.project')),
            ],
            options={
                'db_table': 'progress_updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='progress_updates/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='operations.progressupdate')),
            ],
            options={
                'db_table': 'progress_update_images',
                'ordering': ['created_at'],
            },
        ),
    ]
