# Generated by Django 4.2.29 on 2026-04-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectphase_alter_project_current_phase'),
        ('operations', '0003_progressupdate_progressupdateimage'),
    ]

    operations = [
        # Drop old CharField column, then add new FK column
        migrations.RemoveField(
            model_name='progressupdate',
            name='phase',
        ),
        migrations.AddField(
            model_name='progressupdate',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_updates', to='core.projectphase'),
        ),
    ]
