# Generated by Django 4.2.29 on 2026-04-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
    ]
