# Generated by Django 4.2.29 on 2026-04-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_phase',
            field=models.CharField(choices=[('preparation', 'เตรียมงาน'), ('foundation', 'ฐานราก'), ('structure', 'โครงสร้าง'), ('roofing', 'หลังคา'), ('electrical', 'ไฟฟ้า'), ('plumbing', 'ประปา'), ('plastering', 'ฉาบปูน'), ('tiling', 'กระเบื้อง'), ('painting', 'ทาสี'), ('finishing', 'ตกแต่ง'), ('cleanup', 'ทำความสะอาด'), ('handover', 'ส่งมอบ')], default='preparation', max_length=30),
        ),
    ]
