# Generated by Django 4.2.29 on 2026-04-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_current_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(default='📌', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='ลำดับเฟส (น้อย→มาก)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='core.project')),
            ],
            options={
                'db_table': 'project_phases',
                'ordering': ['order', 'id'],
                'unique_together': {('project', 'name')},
            },
        ),
        # Drop old CharField column, then add new FK column
        migrations.RemoveField(
            model_name='project',
            name='current_phase',
        ),
        migrations.AddField(
            model_name='project',
            name='current_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_projects', to='core.projectphase'),
        ),
    ]
