# Generated by Django 4.2.29 on 2026-04-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_phasetemplate_remove_projectphase_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='progress',
            field=models.IntegerField(default=0, help_text='Phase progress 0-100'),
        ),
    ]
